resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        max-wait-duration-in-half-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 2s
    instances:
      productos:
        base-config: defecto   
  timelimiter:
    configs:
      defecto:
        timeout-duration: 2s
    instances:
      productos:
        base-config: defecto   


spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:          - Path=/api/productos/**
         # - Header= token, \d+
         # - Header=Content-Type,application/json
         # - Method=GET,POST
         # - Query= color
         # - Cookie=color,azul
        filters:
          - name: CircuitBreaker
            args:
              name: productos
              statusCodes: 500
              #fallbackUri: forward:/api/items/ver/9/cantidad/5
          - StripPrefix=2
          - name: Ejemplo
            args:
              mensaje: Hola Bebe
              cookieNombre: usuario
              cookieValor: CristianManuel21
      - id: servicio-item
        uri: lb://servicio-item
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2
          - AddRequestHeader=token-request, 123456
          - AddResponseHeader=token-response, 12345678
          - AddRequestParameter=nombre, cristian
          
      - id: servicio-oauth
        uri: lb://servicio-oauth
        predicates:
          - Path=/api/security/**
        filters:
          - StripPrefix=2
          
          
      - id: servicio-usuarios
        uri: lb://servicio-usuarios
        predicates:
          - Path=/api/usuarios/**
        filters:
          - StripPrefix=2
          